# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from mychrome import MyChrome
from settings.main_settings import *
from api import XPATHs

class TestLogin():
    # Before test
    def setup_method(self, method):
        self.driver     = MyChrome(proxy='192.126.209.165:8800',agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',timeout=30)
        self.username   = 'andrew.giuliano0187@cartone.life'
        self.password   = 'qkbpuTA=#33'

        # {'email_id': 4035, 'proxy': '192.126.209.165:8800', 'password': 'qkbpuTA=#33', 
        # 'agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36', 
        # 'agent_id': 615, 'connection': 'HTTP', 'proxy_id': 8123, 'type': 'PRIVATE', 'email': 'andrew.giuliano0187@cartone.life'}

    # After Test
    def teardown_method(self, method):
        self.driver.quit()
  
    # Test Method
    def test_login(self):
        # Go to main site page
        self.driver.navigateToUrl(MAIN_SITE)
        # check the page loaded successfully
        assert self.driver.isPageLoadSuccess() == True
        
        # Check accept-button
        self.driver.isAcceptButtonPresent()

        # Check signin-button is displayed and click

        assert self.driver.checkIfElementIsPresent(XPATHs['signin_button']) == True

        # Check username input box is displayed and type username
        assert self.driver.checkIfElementIsDisplayed(XPATHs['email_input']) == True
        self.driver.typeTextandEnter(XPATHs['email_input'],self.username)

        # Check password input box is displayed and type password
        assert self.driver.checkIfElementIsDisplayed(XPATHs['password_input']) == True
        self.driver.typeTextandEnter(XPATHs['password_input'],self.password)

        # Check account summary view for sign success
        assert self.driver.checkIfElementIsDisplayed(XPATHs['summary_view_for_check_signed_in']) == True